// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwOozqWbyDNk51m2w0s1520cIEnGQMok',
    appId: '1:310657220512:web:a479155bad72af08f3aec5',
    messagingSenderId: '310657220512',
    projectId: 'flutter-3577d',
    authDomain: 'flutter-3577d.firebaseapp.com',
    storageBucket: 'flutter-3577d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJRcwpqFAE8nnUqyTwbihiv6kBUfQUNiM',
    appId: '1:310657220512:android:5b77942c632b2cf7f3aec5',
    messagingSenderId: '310657220512',
    projectId: 'flutter-3577d',
    storageBucket: 'flutter-3577d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADVFen7eTolkHwV84h1owwb8EthomPkug',
    appId: '1:310657220512:ios:623085996daf4445f3aec5',
    messagingSenderId: '310657220512',
    projectId: 'flutter-3577d',
    storageBucket: 'flutter-3577d.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADVFen7eTolkHwV84h1owwb8EthomPkug',
    appId: '1:310657220512:ios:7c572e71949a3daaf3aec5',
    messagingSenderId: '310657220512',
    projectId: 'flutter-3577d',
    storageBucket: 'flutter-3577d.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
